---
- name: "Create VLAN"
  hosts: all
  gathẻ_facts: no

  tasks:
  - name: Show Vlan
    cisco.ios.ios_command:
    commands:
    - show vlan
    register: show_vlan
    
  - debug:
    msg: "{{show_vlan.stdout_lines}}"
